tabBarBackgroundImageStyleを追加した
CureApp/react-native-router-flux pull request #1
Opened 2016-11-29 15:21 UTC by YutamaKotaro

新しくタブバーの背景画像にスタイルを適用するためのtabBarBackgroundImageStyleを追加しました。

使用例です。

```
                        <Scene
                            key="tabs"
                            tabs
                            tabBarBackgroundImage={IMAGES.BACKGROUND.TAB_BAR}
                            tabBarBackgroundImageStyle={{
                                     height: 50,
                                     width: undefined
                            }}
                            tabBarStyle={styles.tabBar}
                        >
```

2016-11-30 23:17 UTC, januswel requested changes
細かいのですが、先に対応してバグを減らしたいのでご対応お願いいたします

2016-11-30 23:17 UTC, januswel commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
`tabBarBackgroundImageStyle` が存在することを確認したほうがよいですね

2016-12-01 13:50 UTC, YutamaKotaro commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
すみません・・・！！たしかにその通りです。
あまりかんがえていませんでした。ご指摘ありがとうございます！

2016-12-01 14:51 UTC, YutamaKotaro commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
すみません、理解のために質問させてください。
tabBarBackgroundImageStyle未指定の場合は、undefinedとなってstyleが適用されないのでこれでいいと思っていたのですが、tabBarBackgroudnImageStyleの存在確認はどういった目的があるのでしょうか？

2016-12-01 15:00 UTC, januswel commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
ごめんなさい、細かい挙動を確認できていないのですが、

- `style` prop にはオブジェクトか配列でないと指定できないのではないかと思った点
- ↑が問題なくても指定しないと強制的に `tabBarBackgroundImageStyle` が  `undefined` になってしまっていわゆるデフォルトスタイルを上書きしてしまうのではないかという点

が心配で指摘しました。

2016-12-01 15:26 UTC, YutamaKotaro commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
1点目については

```
tabBarBackgroundImageStyle: Image.propTypes.style,
```

こちらで型チェックされるのでここを通過できるものであれば指定できます！

2点目については、デフォルトスタイルはImageには存在しないため問題ないと思います。

2016-12-01 15:49 UTC, januswel commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
> 2点目については、デフォルトスタイルはImageには存在しないため問題ないと思います。

こちらは把握しました、ご指摘ありがとうございます。

> style prop にはオブジェクトか配列でないと指定できないのではないかと思った点

`Image` の `style` prop に明示的に undefined を渡しても怒られないのかなという疑問です
大丈夫なんでしょうか… ?

2016-12-01 16:05 UTC, YutamaKotaro commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
なるほど・・！！。StyleSheet.createでは怒られますが、

```
tabBarBackgroundImageStyle={undefined}
```

であれば問題ないです！

2016-12-01 16:52 UTC, januswel commented on src/TabBar.js
> +              style={state.tabBarBackgroundImageStyle}
ご確認ありがとうございます！

2016-12-01 16:52 UTC, januswel approved these changes

2016-12-01 16:52 UTC, januswel commented
大丈夫かなと思うので merge しちゃいます

2016-12-01 16:52 UTC, merged